// Code generated by schemaGen. DO NOT EDIT.

package scan

import (
	"github.com/Azure/container-kit/pkg/mcp/core/tools"
)

// Generated schemas for tool arguments
var (

	// AtomicScanSecretsArgsSchema is the generated JSON schema for AtomicScanSecretsArgs
	AtomicScanSecretsArgsSchema = &tools.JSONSchema{
		Type:        "object",
		Title:       "Atomic Scan Secrets",
		Description: "",
		Properties: map[string]*tools.JSONSchema{
			"scan_path": {
				Type:        "string",
				Description: "Path to scan (default: session workspace)",
			},
			"file_patterns": {
				Type:        "array",
				Description: "File patterns to include in scan (e.g., '*.py', '*.js')",
			},
			"exclude_patterns": {
				Type:        "array",
				Description: "File patterns to exclude from scan",
			},
			"scan_dockerfiles": {
				Type:        "boolean",
				Description: "Include Dockerfiles in scan",
			},
			"scan_manifests": {
				Type:        "boolean",
				Description: "Include Kubernetes manifests in scan",
			},
			"scan_source_code": {
				Type:        "boolean",
				Description: "Include source code files in scan",
			},
			"scan_env_files": {
				Type:        "boolean",
				Description: "Include .env files in scan",
			},
			"suggest_remediation": {
				Type:        "boolean",
				Description: "Provide remediation suggestions",
			},
			"generate_secrets": {
				Type:        "boolean",
				Description: "Generate Kubernetes Secret manifests",
			},
		},
		Required:             []string{},
		AdditionalProperties: &[]bool{false}[0],
	}
)
