// Code generated by schemaGen. DO NOT EDIT.

package scan

import (
	"github.com/Azure/container-kit/pkg/mcp/core/tools"
)

// Generated schemas for tool arguments
var (

	// AtomicScanImageSecurityArgsSchema is the generated JSON schema for AtomicScanImageSecurityArgs
	AtomicScanImageSecurityArgsSchema = &tools.JSONSchema{
		Type:        "object",
		Title:       "Atomic Scan Image Security",
		Description: "",
		Properties: map[string]*tools.JSONSchema{
			"image_name": {
				Type:        "string",
				Description: "Docker image name/tag to scan (e.g., nginx:latest)",
				// Required field
			},
			"severity_threshold": {
				Type:        "string",
				Description: "Minimum severity to report (LOW,MEDIUM,HIGH,CRITICAL)",
			},
			"vuln_types": {
				Type:        "array",
				Description: "Types of vulnerabilities to scan for (os,library,app)",
			},
			"include_fixable": {
				Type:        "boolean",
				Description: "Include only fixable vulnerabilities",
			},
			"max_results": {
				Type:        "integer",
				Description: "Maximum number of vulnerabilities to return",
			},
			"include_remediations": {
				Type:        "boolean",
				Description: "Include remediation recommendations",
			},
			"generate_report": {
				Type:        "boolean",
				Description: "Generate detailed security report",
			},
			"fail_on_critical": {
				Type:        "boolean",
				Description: "Fail if critical vulnerabilities found",
			},
		},
		Required: []string{
			"image_name",
		},
		AdditionalProperties: &[]bool{false}[0],
	}
)
