# This ConfigMap is used to store non-sensitive configuration data for the application.
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
  labels:
    app.kubernetes.io/name: app
    kubernetes.azure.com/generator: container-copilot
data: