#use file for sensitive data like passwords, tokens, etc.
apiVersion: v1
kind: Secret
metadata:
  name: secret-ref
  namespace: default
  labels:
    app.kubernetes.io/name: app
    kubernetes.azure.com/generator: container-copilot
type: Opaque
# auto-converts to base64
stringData:
