// Code generated by schemaGen. DO NOT EDIT.

package deploy

import (
	"github.com/Azure/container-kit/pkg/mcp/domain/types/tools"
)

// Generated schemas for tool arguments
var (

	// AtomicCheckHealthArgsSchema is the generated JSON schema for AtomicCheckHealthArgs
	AtomicCheckHealthArgsSchema = &tools.JSONSchema{
		Type:        "object",
		Title:       "Atomic Check Health",
		Description: "",
		Properties: map[string]*tools.JSONSchema{
			"namespace": {
				Type:        "string",
				Description: "Kubernetes namespace (default: default)",
			},
			"app_name": {
				Type:        "string",
				Description: "Application name for label selection",
			},
			"label_selector": {
				Type:        "string",
				Description: "Custom label selector (e.g., app=myapp,version=v1)",
			},
			"include_services": {
				Type:        "boolean",
				Description: "Include service health checks (default: true)",
			},
			"include_events": {
				Type:        "boolean",
				Description: "Include pod events in analysis (default: true)",
			},
			"wait_for_ready": {
				Type:        "boolean",
				Description: "Wait for pods to become ready",
			},
			"wait_timeout": {
				Type:        "integer",
				Description: "Wait timeout in seconds (default: 300)",
			},
			"detailed_analysis": {
				Type:        "boolean",
				Description: "Perform detailed container and condition analysis",
			},
			"include_logs": {
				Type:        "boolean",
				Description: "Include recent container logs in analysis",
			},
			"log_lines": {
				Type:        "integer",
				Description: "Number of log lines to include (default: 50)",
			},
		},
		Required:             []string{},
		AdditionalProperties: &[]bool{false}[0],
	}
)
