# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    # Run on the 1st and 15th of each month at 09:00 UTC.
    schedule:
      interval: "cron"
      cronjob: "0 9 1,15 * *"
    # Wait 7 days after a release before proposing it
    cooldown:
      default-days: 7
    groups:
      npm-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      npm-security-minor-patch:
        applies-to: security-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    # Run on the 1st and 15th of each month at 09:00 UTC.
    schedule:
      interval: "cron"
      cronjob: "0 9 1,15 * *"
    # Wait 7 days after a release before proposing it
    cooldown:
      default-days: 7
    groups:
      github-actions-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
