version: 2

linters:
  enable:
    - staticcheck
    - revive
    - gosec
    - unused
    - gocyclo
    - errcheck
    - govet
    - godox

linters-settings:
  gocyclo:
    min-complexity: 25
  godox:
    keywords:
      - TODO
      - HACK
      - FIXME

issues:
  max-issues-per-linter: 10
  max-same-issues: 5
  new: true
  new-from-rev: "main"

run:
  tests: true
  timeout: 5m
  go: "1.21"
