version: "2"

run:
  timeout: 10m
  issues-exit-code: 1
  tests: true
  go: "1.24"

linters-settings:
  gocyclo:
    min-complexity: 15

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  lll:
    line-length: 120

  gci:
    sections:
      - standard
      - default
      - prefix(github.com/Azure/container-kit)

  stylecheck:
    checks: ["all"]

  revive:
    rules:
      - name: file-length
        arguments: [800]
      - name: function-length
        arguments: [50]
      - name: cyclomatic
        arguments: [15]
      - name: argument-limit
        arguments: [5]
      - name: cognitive-complexity
        arguments: [10]
      - name: deep-exit
        disabled: false
      - name: exported
        disabled: false
      - name: unused-parameter
        disabled: false
      - name: unused-receiver
        disabled: false
      - name: var-naming
        disabled: false
      - name: package-comments
        disabled: false

  funlen:
    lines: 80
    statements: 50

  nestif:
    min-complexity: 4

  goimports:
    local-prefixes: github.com/Azure/container-kit

  gosec:
    excludes:
      - G104 # Unhandled errors - we have custom error handling
      - G204 # Subprocess with variable - needed for Docker commands

linters:
  enable:
    - bodyclose
    - contextcheck
    - errcheck
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goimports
    - golint
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nestif
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - deadcode
    - structcheck
    - lll
    - gci
    - exportloopref
    - goerr113
    - wsl

  disable:
    - exhaustive  # Too strict for our use case
    - exhaustivestruct  # Too strict for our use case
    - testpackage  # We allow tests in same package

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
  new: false

  exclude-rules:
    # Exclude non-MCP packages from enhanced linting rules
    - path: ^(?!pkg/mcp/).*
      linters:
        - revive
        - stylecheck
        - gocyclo
        - gocognit
        - funlen
        - gochecknoglobals
        - gochecknoinits
        - gosec
        - goconst
        - godot
        - nestif
        - prealloc
        - unparam
        - unused
        - varcheck
        - deadcode
        - structcheck
        - lll
        - exportloopref
        - goerr113
        - wsl
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - funlen
        - gocognit
        - dupl

    # Exclude some linters from running on generated files
    - path: \.pb\.go$
      linters:
        - lll
        - gocyclo
        - funlen

    # Exclude package comment rules for internal packages
    - path: internal/
      text: "should have a package comment"
      linters:
        - stylecheck
        - revive

    # Allow long lines in tool definitions
    - path: tools/
      linters:
        - lll

    # Allow globals in main packages
    - path: cmd/
      linters:
        - gochecknoglobals

  exclude-dirs:
    - vendor
    - third_party
    - .git
    - bin
    - dist
    - examples
    - tools/external

  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*_gen\\.go$"
