version: "2"
run:
  go: "1.24"
  tests: true
linters:
  disable:
    - unused
    - ineffassign      # Disable ineffectual assignment checks
    - depguard         # Disable import restrictions after simplification
  enable:
    - revive
    - staticcheck      # Enable advanced static analysis
    - errcheck         # Enable error checking

linters-settings:
  depguard:
    rules:
      main:
        files:
          - "$all"
        allow:
          - "$gostd"
          - "github.com/Azure/container-kit"
          - "github.com/localrivet/gomcp"
          - "github.com/rs/zerolog"
          - "github.com/stretchr/testify"
          - "github.com/joho/godotenv"
          - "github.com/spf13/cobra"
          - "go.etcd.io/bbolt"
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - govet
        path: _test\.go
      - linters:
          - govet
        path: cmd/
      - linters:
          - govet
        path: tools/
      - linters:
          - revive
        path: pkg/mcp/security/types\.go
        text: "stutters"
    paths:
      - .*\.pb\.go$
      - .*_gen\.go$
      - cmd/*
      - vendor
      - .git
      - bin
      - dist
      - tools
      - tools/linters
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
