version: 2

linters:
  enable:
    # Core linters
    - staticcheck
    - revive
    - gosec
    - unused
    - gocyclo
    - errcheck
    - govet
    - godox
    # Additional strict linters for quality
    - gofmt
    - goimports
    - gofumpt
    - ineffassign
    - misspell
    - unconvert
    - unparam
    - gocritic
    - gosimple
    - typecheck
    - dupl
    - goconst
    - gocognit
    - nestif
    - prealloc
    - nolintlint
    - whitespace
    - wsl
    - mnd  # Replaced deprecated gomnd
    # Security and best practices
    - bodyclose
    - rowserrcheck
    - sqlclosecheck
    - nilerr
    - forcetypeassert
    - copyloopvar  # Replaced deprecated exportloopref

  disable:
    - varnamelen  # Too noisy for short variable names
    - exhaustivestruct  # Too strict for external structs
    - paralleltest  # Not always applicable
    - testpackage  # Allow internal testing

linters-settings:
  gocyclo:
    min-complexity: 15  # Stricter than default (10)
  gocognit:
    min-complexity: 20  # Cognitive complexity limit
  nestif:
    min-complexity: 5   # Nested if complexity
  gofumpt:
    extra-rules: true
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
      - diagnostic
    disabled-checks:
      - unnamedResult  # Sometimes unnamed results are clearer
      - whyNoLint     # Allow missing explanations for some cases
  revive:
    severity: error
    rules:
      - name: exported
        arguments: ["checkPrivateReceivers", "disableStutteringCheck"]
      - name: package-comments
      - name: var-naming
      - name: indent-error-flow
      - name: error-return
      - name: error-naming
      - name: if-return
      - name: range-val-in-closure
      - name: context-as-argument
      - name: context-keys-type
  gosec:
    confidence: medium
    severity: medium
    excludes:
      - G204  # Command injection - we have legitimate subprocess calls
      - G304  # File path traversal - we handle paths securely
  godox:
    keywords:
      - TODO
      - HACK
      - FIXME
      - BUG
      - OPTIMIZE
  dupl:
    threshold: 150  # Allow some duplication
  goconst:
    min-len: 3
    min-occurrences: 3
  mnd:
    checks:
      - argument
      - case
      - condition
      - operation
      - return
      - assign
    ignored-numbers: "0,1,2,8,10,16,24,32,64,100,1000,1024"
  prealloc:
    simple: true
    range-loops: true
    for-loops: false

issues:
  max-issues-per-linter: 20  # Increased for stricter linting
  max-same-issues: 10
  new: false  # Check all issues, not just new ones
  exclude-dirs:
    - vendor
    - .git
    - bin
    - dist
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*_gen\\.go$"
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - goconst
        - mnd
    # Exclude godox from vendor
    - path: vendor/
      linters:
        - godox
    # Exclude specific directories
    - path: hack/
      linters:
        - gosec
        - errcheck
    - path: scripts/
      linters:
        - gosec
        - errcheck
  exclude:
    # Exclude common false positives
    - "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*print(f|ln)?|os\\.(Un)?Setenv). is not checked"
    - "func name will be used as test\\.Test.* by other packages, and that stutters; consider calling this"

run:
  tests: true
  timeout: 10m  # Increased timeout for strict linting
  go: "1.21"
