version: "2"
run:
  go: "1.24"
  tests: true
linters:
  disable:
    - errcheck
    - unused
    - ineffassign      # Disable ineffectual assignment checks
    - staticcheck      # Temporarily disable advanced static analysis
  settings:
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - govet
        path: _test\.go
      - linters:
          - govet
        path: cmd/
      - linters:
          - govet
        path: tools/
    paths:
      - .*\.pb\.go$
      - .*_gen\.go$
      - cmd/*
      - vendor
      - .git
      - bin
      - dist
      - tools
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
