version: "2"
run:
  go: "1.24"
  tests: true
linters:
  disable:
    - unused
    - ineffassign      # Disable ineffectual assignment checks
  enable:
    - revive
    - depguard
    - staticcheck      # Enable advanced static analysis per TODO.md
    - errcheck         # Enable error checking per TODO.md

linters-settings:
  depguard:
    rules:
      non-internal:
        files:
          - "pkg/mcp/**"
          - "!pkg/mcp/internal/**"
        deny:
          - pkg: "github.com/Azure/container-kit/pkg/mcp/internal"
            desc: "Internal packages should not be imported by external packages"
          - pkg: "github.com/Azure/container-kit/pkg/mcp/core"
            desc: "Core should only be imported by internal packages"
      api-only:
        files:
          - "pkg/mcp/api/**"
        deny:
          - pkg: "github.com/Azure/container-kit/pkg/mcp/internal"
            desc: "API package should not depend on internal packages"
          - pkg: "github.com/Azure/container-kit/pkg/mcp/core"
            desc: "API package should not depend on core packages"
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - govet
        path: _test\.go
      - linters:
          - govet
        path: cmd/
      - linters:
          - govet
        path: tools/
      - linters:
          - revive
        path: pkg/mcp/security/types\.go
        text: "stutters"
    paths:
      - .*\.pb\.go$
      - .*_gen\.go$
      - cmd/*
      - vendor
      - .git
      - bin
      - dist
      - tools
      - tools/linters
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
