# .goreleaser.yml
# Build configuration for container-kit

version: 2

project_name: container-kit

before:
  hooks:
    # Ensure module download and verify
    - go mod download
    - go mod verify

builds:
  # MCP Server binary (only binary released)
  - id: container-kit-mcp
    main: ./cmd/mcp-server
    binary: container-kit-mcp
    tags:
      - mcp
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.Version={{.Version}} -X main.GitCommit={{.Commit}} -X main.BuildTime={{.Date}}
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - id: mcp
    # Use explicit naming to reflect MCP server artifact
    name_template: "container-kit-mcp_{{ .Os }}_{{ .Arch }}"
    builds:
      - container-kit-mcp
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE*
      - README.md

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
  groups:
    - title: '🚀 Features'
      regexp: '^feat'
    - title: '🐛 Bug Fixes'
      regexp: '^fix'
    - title: '🔨 Refactoring'
      regexp: '^refactor'
    - title: '⚡ Performance Improvements'
      regexp: '^perf'
    - title: '🔐 Security'
      regexp: '^security'
    - title: 'Other Changes'
      order: 999

release:
  github:
    owner: Azure
    name: container-kit

  # Release notes template
  header: |
    ## Container Kit {{ .Tag }}

    Welcome to Container Kit {{ .Tag }}! This release includes several improvements and bug fixes.

    ### Installation (MCP Server)

    The MCP server binary (container-kit-mcp) is provided for Linux, macOS (Intel & ARM), and Windows (amd64 & arm64).

    #### Quick Install (Windows PowerShell)
    ```powershell
    Set-ExecutionPolicy Bypass -Scope Process -Force; Invoke-WebRequest -Uri https://raw.githubusercontent.com/Azure/container-kit/main/scripts/setup-vscode.ps1 -OutFile setup-vscode.ps1; ./setup-vscode.ps1; Remove-Item setup-vscode.ps1
    ```

    #### Quick Install (macOS / Linux)
    ```bash
    curl -sSL https://raw.githubusercontent.com/Azure/container-kit/main/scripts/setup-vscode.sh | bash
    ```

    #### Manual Install
    1. Download the archive matching your platform.
    2. Extract the binary and place it on your PATH (e.g. /usr/local/bin or $HOME/bin).
    3. Verify: `container-kit-mcp --help`

    #### Documentation
    - User Guide: https://github.com/Azure/container-kit/blob/{{ .Tag }}/USER_GUIDE.md
    
    For the complete, always up-to-date setup (including configuration, troubleshooting, and updates) please follow all steps in the User Guide above.

  footer: |
    ## Thanks!

    Thanks to all contributors who made this release possible!

    **Full Changelog**: https://github.com/Azure/container-kit/compare/{{ .PreviousTag }}...{{ .Tag }}

  # Set draft to true for manual review before publishing
  draft: false

snapshot:
  version_template: "{{ .Tag }}-next"

# Announce releases
announce:
  skip: true

# Automatically close milestone with matching name
milestones:
  - close: true
    fail_on_error: false

# GitHub Action specific configuration
github_urls:
  download: https://github.com

metadata:
  mod_timestamp: '{{ .CommitTimestamp }}'
