repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
    exclude: '^(pkg/mcp/infra/templates/|pkg/mcp/templates/|resources/templates/|templates/).*\.yaml$'  # Exclude Go template files
  - id: check-added-large-files
    args: ['--maxkb=1000']

- repo: https://github.com/golangci/golangci-lint
  rev: v1.62.0
  hooks:
  - id: golangci-lint
    args: ['--fix']
    exclude: '^tools/linters/.*'

- repo: local
  hooks:
  - id: go-fmt
    name: go fmt
    entry: bash -c 'gofmt -s -w .'
    language: system
    types: [go]
    pass_filenames: false

  - id: go-imports
    name: goimports
    entry: bash -c 'goimports -w .'
    language: system
    types: [go]
    pass_filenames: false

  - id: go-mod-tidy
    name: go mod tidy
    entry: bash -c 'go mod tidy'
    language: system
    types: [go]
    pass_filenames: false

  # Schema generation is handled in CI to avoid pre-commit loops
  # Run 'make generate' manually when changing Args structs

  - id: check-generated-schemas
    name: Check generated schemas
    entry: bash -c 'git add -N pkg/mcp/internal/**/generated_*.go 2>/dev/null; if [ -n "$(git diff --name-only -- "pkg/mcp/internal/**/generated_*.go")" ]; then echo "Generated schemas have uncommitted changes. Please stage them."; exit 1; fi'
    language: system
    always_run: true
    pass_filenames: false
