apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .AppName }}-config
  namespace: {{ .Namespace }}
  labels:
    app: {{ .AppName }}
data:
  {{- range $key, $value := .Data }}
  {{ $key }}: |
{{ $value | indent 4 }}
  {{- end }}
