apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .AppName }}
  namespace: {{ .Namespace }}
  labels:
    app: {{ .AppName }}
spec:
  replicas: {{ .Replicas }}
  selector:
    matchLabels:
      app: {{ .AppName }}
  template:
    metadata:
      labels:
        app: {{ .AppName }}
    spec:
      containers:
      - name: {{ .AppName }}
        image: {{ .Image }}
        ports:
        - containerPort: {{ .ContainerPort }}
        {{- if .Resources }}
        resources:
          {{- if .Resources.Limits }}
          limits:
            {{- if .Resources.Limits.CPU }}
            cpu: {{ .Resources.Limits.CPU }}
            {{- end }}
            {{- if .Resources.Limits.Memory }}
            memory: {{ .Resources.Limits.Memory }}
            {{- end }}
          {{- end }}
          {{- if .Resources.Requests }}
          requests:
            {{- if .Resources.Requests.CPU }}
            cpu: {{ .Resources.Requests.CPU }}
            {{- end }}
            {{- if .Resources.Requests.Memory }}
            memory: {{ .Resources.Requests.Memory }}
            {{- end }}
          {{- end }}
        {{- end }}
        {{- if .EnvironmentVars }}
        env:
        {{- range $key, $value := .EnvironmentVars }}
        - name: {{ $key }}
          value: {{ $value }}
        {{- end }}
        {{- end }}
