// Code generated by schemaGen. DO NOT EDIT.

package example

import (
	"github.com/Azure/container-kit/pkg/mcp/domain/types/tools"
)

// Generated schemas for tool arguments
var (

	// ExampleToolArgsSchema is the generated JSON schema for ExampleToolArgs
	ExampleToolArgsSchema = &tools.JSONSchema{
		Type:        "object",
		Title:       "Example Tool",
		Description: "",
		Properties: map[string]*tools.JSONSchema{
			"name": {
				Type:        "string",
				Description: "The name of the person to greet",
				// Required field
			},
			"message": {
				Type:        "string",
				Description: "Optional custom greeting message",
			},
			"count": {
				Type:        "integer",
				Description: "Number of times to repeat the greeting",
				// Required field
			},
			"loud": {
				Type:        "boolean",
				Description: "Whether to shout the greeting",
			},
		},
		Required: []string{
			"name",
			"count",
		},
		AdditionalProperties: &[]bool{false}[0],
	}
)
