// Code generated by schemaGen. DO NOT EDIT.

package conversation

import (
	"github.com/Azure/container-kit/pkg/mcp/domain/tools"
)

// Generated schemas for tool arguments
var (

	// ChatToolArgsSchema is the generated JSON schema for ChatToolArgs
	ChatToolArgsSchema = &tools.JSONSchema{
		Type:        "object",
		Title:       "Chat Tool",
		Description: "",
		Properties: map[string]*tools.JSONSchema{
			"message": {
				Type:        "string",
				Description: "Your message to the assistant",
				// Required field
			},
			"session_id": {
				Type:        "string",
				Description: "Session ID for continuing a conversation (optional for first message)",
			},
		},
		Required: []string{
			"message",
		},
		AdditionalProperties: &[]bool{false}[0],
	}
)
