# Development environment configuration overrides
environment: development

overrides:
  scoring:
    dockerfile:
      category_weights:
        correctness: 0.40  # Focus on correctness in development
        efficiency: 0.20
        security: 0.15
        maintainability: 0.15
        completeness: 0.10

  sampling:
    max_candidates: 3
    timeout_ms: 5000
    early_stop_threshold: 0.85