# Production environment configuration overrides
environment: production

overrides:
  scoring:
    dockerfile:
      category_weights:
        security: 0.35  # Higher weight on security in production
        correctness: 0.30
        efficiency: 0.20
        maintainability: 0.10
        completeness: 0.05

  sampling:
    max_candidates: 5
    timeout_ms: 10000
    early_stop_threshold: 0.95