mcpServers:
  container-kit:
    type: "local"
    command: "./containerization-assist-mcp"
    args: []
  
  filesystem:
    type: "builtin"
    name: "fs"
    options:
      allowed_directories: ["/tmp", ".", "/home/runner/work"]
  
  bash:
    type: "builtin"
    name: "bash"

model: "azure:${env://AZURE_OPENAI_DEPLOYMENT_ID}"
provider-api-key: "${env://AZURE_OPENAI_KEY}"
provider-url: "${env://AZURE_OPENAI_ENDPOINT}"
