// Code generated by schemaGen. DO NOT EDIT.

package analyze

import (
	"github.com/Azure/container-kit/pkg/mcp/core/tools"
)

// Generated schemas for tool arguments
var (

	// AtomicValidateDockerfileArgsSchema is the generated JSON schema for AtomicValidateDockerfileArgs
	AtomicValidateDockerfileArgsSchema = &tools.JSONSchema{
		Type:        "object",
		Title:       "Atomic Validate Dockerfile",
		Description: "",
		Properties: map[string]*tools.JSONSchema{
			"dockerfile_path": {
				Type:        "string",
				Description: "Path to Dockerfile (default: session workspace/Dockerfile)",
			},
			"dockerfile_content": {
				Type:        "string",
				Description: "Dockerfile content to validate (alternative to path)",
			},
			"use_hadolint": {
				Type:        "boolean",
				Description: "Use Hadolint for advanced validation",
			},
			"severity": {
				Type:        "string",
				Description: "Minimum severity to report (info, warning, error)",
			},
			"ignore_rules": {
				Type:        "array",
				Description: "Hadolint rules to ignore (e.g., DL3008, DL3009)",
			},
			"trusted_registries": {
				Type:        "array",
				Description: "List of trusted registries for base image validation",
			},
			"check_security": {
				Type:        "boolean",
				Description: "Perform security-focused checks",
			},
			"check_optimization": {
				Type:        "boolean",
				Description: "Check for image size optimization opportunities",
			},
			"check_best_practices": {
				Type:        "boolean",
				Description: "Validate against Docker best practices",
			},
			"include_suggestions": {
				Type:        "boolean",
				Description: "Include remediation suggestions",
			},
			"generate_fixes": {
				Type:        "boolean",
				Description: "Generate corrected Dockerfile",
			},
		},
		Required:             []string{},
		AdditionalProperties: &[]bool{false}[0],
	}
)
