// Code generated by schemaGen. DO NOT EDIT.

package analyze

import (
	"github.com/Azure/container-kit/pkg/mcp/core/tools"
)

// Generated schemas for tool arguments
var (

	// AnalyzeRepositoryArgsSchema is the generated JSON schema for AnalyzeRepositoryArgs
	AnalyzeRepositoryArgsSchema = &tools.JSONSchema{
		Type:        "object",
		Title:       "Analyze Repository",
		Description: "",
		Properties: map[string]*tools.JSONSchema{
			"path": {
				Type:        "string",
				Description: "Local directory path or GitHub URL",
				// Required field
			},
			"context": {
				Type:        "string",
				Description: "Additional context about the application",
			},
			"language": {
				Type:        "string",
				Description: "Primary programming language hint",
			},
			"framework": {
				Type:        "string",
				Description: "Framework hint (e.g., express, django)",
			},
			"skip_file_tree": {
				Type:        "boolean",
				Description: "Skip generating file tree for performance",
			},
			"sandbox": {
				Type:        "boolean",
				Description: "Run analysis in sandboxed environment",
			},
		},
		Required: []string{
			"path",
		},
		AdditionalProperties: &[]bool{false}[0],
	}
)
