name: 'PR Status Generator'
description: 'Generates and posts comprehensive PR status comments'
inputs:
  github-token:
    description: 'GitHub token for posting comments'
    required: true
  run-id:
    description: 'GitHub Actions run ID'
    required: true
  architecture-score:
    description: 'Architecture quality score'
    required: false
  architecture-status:
    description: 'Architecture status (pass/warning/fail)'
    required: false
  architecture-details:
    description: 'Architecture analysis details'
    required: false
  coverage-total:
    description: 'Total test coverage percentage'
    required: false
  coverage-status:
    description: 'Coverage status (pass/warning/fail)'
    required: false
  security-secrets:
    description: 'Security secrets scan results'
    required: false
  security-vulnerabilities:
    description: 'Security vulnerability scan results'
    required: false
  lint-results:
    description: 'Lint check results'
    required: false
  quality-results:
    description: 'Quality gate results'
    required: false
  canary-time:
    description: 'Canary execution time'
    required: false
  total-time:
    description: 'Total pipeline execution time'
    required: false
runs:
  using: "composite"
  steps:
    - name: Download artifacts for status analysis
      uses: actions/download-artifact@v4
      with:
        pattern: "*-${{ inputs.run-id }}"
        path: artifacts
      continue-on-error: true

    - name: Prepare CI Status Data
      id: ci-status
      shell: bash
      run: |
        echo "📊 Preparing comprehensive CI status data..."

        # Extract security scan results
        SECURITY_SECRETS="${{ inputs.security-secrets }}"
        SECURITY_VULNERABILITIES="${{ inputs.security-vulnerabilities }}"

        if [ -z "$SECURITY_SECRETS" ]; then
          if [ -f "artifacts/security-reports-${{ inputs.run-id }}/gitleaks-report.json" ]; then
            leak_count=$(jq '. | length' artifacts/security-reports-${{ inputs.run-id }}/gitleaks-report.json 2>/dev/null || echo "0")
            if [ "$leak_count" = "0" ]; then
              SECURITY_SECRETS="✅ Passed: No secrets detected"
            else
              SECURITY_SECRETS="❌ Failed: $leak_count secrets detected"
            fi
          else
            SECURITY_SECRETS="⚠️ No Data: Security scan report not available"
          fi
        fi

        if [ -z "$SECURITY_VULNERABILITIES" ]; then
          if [ -f "artifacts/security-reports-${{ inputs.run-id }}/trivy-fs-report.json" ]; then
            vuln_count=$(jq '.Results[].Vulnerabilities | length' artifacts/security-reports-${{ inputs.run-id }}/trivy-fs-report.json 2>/dev/null | awk '{s+=$1} END {print s}' || echo "0")
            if [ "$vuln_count" = "0" ] || [ -z "$vuln_count" ]; then
              SECURITY_VULNERABILITIES="✅ Passed: No vulnerabilities detected"
            else
              SECURITY_VULNERABILITIES="❌ Failed: $vuln_count vulnerabilities detected"
            fi
          else
            SECURITY_VULNERABILITIES="⚠️ No Data: Vulnerability scan report not available"
          fi
        fi

        # Extract coverage results
        COVERAGE_RESULTS="${{ inputs.coverage-total }}"
        if [ -z "$COVERAGE_RESULTS" ]; then
          if [ -f "artifacts/global-coverage-reports-${{ inputs.run-id }}/coverage-summary.txt" ]; then
            total_cov=$(grep "total:" artifacts/global-coverage-reports-${{ inputs.run-id }}/coverage-summary.txt | awk '{print $3}' || echo "unknown")
            COVERAGE_RESULTS="📊 Total Coverage: $total_cov"
          else
            COVERAGE_RESULTS="⚠️ No Data: Coverage report not available"
          fi
        else
          COVERAGE_RESULTS="📊 Total Coverage: ${{ inputs.coverage-total }}% (${{ inputs.coverage-status }})"
        fi

        # Extract lint results (default to passed if we reach this point)
        LINT_RESULTS="${{ inputs.lint-results }}"
        if [ -z "$LINT_RESULTS" ]; then
          LINT_RESULTS="✅ Passed: All linting checks completed successfully"
        fi

        # Extract quality results
        QUALITY_RESULTS="${{ inputs.quality-results }}"
        if [ -z "$QUALITY_RESULTS" ]; then
          QUALITY_RESULTS="⚠️ No Data: Quality metrics not available"
        fi

        # Architecture results
        ARCHITECTURE_RESULTS=""
        if [ -n "${{ inputs.architecture-score }}" ]; then
          ARCHITECTURE_RESULTS="🏗️ Architecture Score: ${{ inputs.architecture-score }}/100 (${{ inputs.architecture-status }})"
          if [ -n "${{ inputs.architecture-details }}" ]; then
            ARCHITECTURE_RESULTS="$ARCHITECTURE_RESULTS\n\n**Details:** ${{ inputs.architecture-details }}"
          fi
        else
          ARCHITECTURE_RESULTS="⚠️ No Data: Architecture analysis not available"
        fi

        # Performance results
        PERFORMANCE_RESULTS=""
        if [ -n "${{ inputs.canary-time }}" ]; then
          PERFORMANCE_RESULTS="⚡ Canary: ${{ inputs.canary-time }}"
          if [ -n "${{ inputs.total-time }}" ]; then
            PERFORMANCE_RESULTS="$PERFORMANCE_RESULTS | Total: ${{ inputs.total-time }}"
          fi
        else
          PERFORMANCE_RESULTS="⚠️ Performance metrics not available"
        fi

        # Save to outputs for the comment generation
        {
          echo "security_secrets<<EOF"
          echo "$SECURITY_SECRETS"
          echo "EOF"
          echo "security_vulnerabilities<<EOF"
          echo "$SECURITY_VULNERABILITIES"
          echo "EOF"
          echo "lint_results<<EOF"
          echo "$LINT_RESULTS"
          echo "EOF"
          echo "coverage_results<<EOF"
          echo "$COVERAGE_RESULTS"
          echo "EOF"
          echo "quality_results<<EOF"
          echo "$QUALITY_RESULTS"
          echo "EOF"
          echo "architecture_results<<EOF"
          echo "$ARCHITECTURE_RESULTS"
          echo "EOF"
          echo "performance_results<<EOF"
          echo "$PERFORMANCE_RESULTS"
          echo "EOF"
        } >> $GITHUB_OUTPUT

    - name: Create or Update PR Comment
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const body = `## 🚀 CI Pipeline Status

          ### 🏗️ Architecture Quality
          ${{ steps.ci-status.outputs.architecture_results }}

          ### 📊 Test Coverage
          ${{ steps.ci-status.outputs.coverage_results }}

          ### 🔒 Security Scan
          **Secrets Detection:** ${{ steps.ci-status.outputs.security_secrets }}
          
          **Vulnerability Scan:** ${{ steps.ci-status.outputs.security_vulnerabilities }}

          ### 🧹 Code Quality
          **Lint Results:** ${{ steps.ci-status.outputs.lint_results }}
          
          **Quality Gates:** ${{ steps.ci-status.outputs.quality_results }}

          ### ⚡ Performance
          ${{ steps.ci-status.outputs.performance_results }}

          ### 🔗 Detailed Results
          [View full pipeline results](https://github.com/${{ github.repository }}/actions/runs/${{ inputs.run-id }})

          ---
          *This comment is automatically updated as CI jobs complete.*
          
          Last updated: ${new Date().toISOString()}`;

          // Find existing comment
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          });

          const botComment = comments.find(comment =>
            comment.user.type === 'Bot' &&
            comment.body.includes('🚀 CI Pipeline Status')
          );

          if (botComment) {
            // Update existing comment
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: botComment.id,
              body: body
            });
            console.log('✅ Updated existing PR comment');
          } else {
            // Create new comment
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: body
            });
            console.log('✅ Created new PR comment');
          }

    - name: Generate Pipeline Summary
      shell: bash
      run: |
        echo "## 🚀 CI Pipeline Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Key Metrics" >> $GITHUB_STEP_SUMMARY
        echo "| Metric | Status |" >> $GITHUB_STEP_SUMMARY
        echo "|--------|--------|" >> $GITHUB_STEP_SUMMARY
        echo "| Architecture | ${{ steps.ci-status.outputs.architecture_results }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Coverage | ${{ steps.ci-status.outputs.coverage_results }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Security | ${{ steps.ci-status.outputs.security_secrets }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Quality | ${{ steps.ci-status.outputs.quality_results }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Performance | ${{ steps.ci-status.outputs.performance_results }} |" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 🔗 Links" >> $GITHUB_STEP_SUMMARY
        echo "- [Full Pipeline Results](https://github.com/${{ github.repository }}/actions/runs/${{ inputs.run-id }})" >> $GITHUB_STEP_SUMMARY
        echo "- [Coverage Reports](https://github.com/${{ github.repository }}/actions/runs/${{ inputs.run-id }}/artifacts)" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY