name: docker_build
description: Basic Docker build workflow
version: 1.0.0
parameters:
  - name: context_path
    type: string
    description: Path to build context
    required: true
  - name: dockerfile
    type: string
    description: Path to Dockerfile
    default: Dockerfile
  - name: image_name
    type: string
    description: Name for the built image
    required: true
  - name: tags
    type: array
    description: Additional tags for the image
    default: []

stages:
  - id: analyze
    name: Analyze repository
    tool: analyze
    parameters:
      path: "{{ .context_path }}"

  - id: build
    name: Build Docker image
    tool: build
    parameters:
      context: "{{ .context_path }}"
      dockerfile: "{{ .dockerfile }}"
      image: "{{ .image_name }}"
      tags: "{{ .tags }}"
    depends_on:
      - analyze

  - id: scan
    name: Security scan
    tool: scan
    parameters:
      image: "{{ .image_name }}"
    depends_on:
      - build
    optional: true
