// Code generated by schemaGen. DO NOT EDIT.

package analyze

import (
	"github.com/Azure/container-kit/pkg/mcp/domain/types/tools"
)

// Generated schemas for tool arguments
var (

	// AtomicAnalyzeRepositoryArgsSchema is the generated JSON schema for AtomicAnalyzeRepositoryArgs
	AtomicAnalyzeRepositoryArgsSchema = &tools.JSONSchema{
		Type:        "object",
		Title:       "Atomic Analyze Repository",
		Description: "",
		Properties: map[string]*tools.JSONSchema{
			"repo_url": {
				Type:        "string",
				Description: "Repository URL (GitHub, GitLab, etc.) or local path",
				// Required field
			},
			"branch": {
				Type:        "string",
				Description: "Git branch to analyze (default: main)",
			},
			"context": {
				Type:        "string",
				Description: "Additional context about the application",
			},
			"language_hint": {
				Type:        "string",
				Description: "Primary programming language hint",
			},
			"shallow": {
				Type:        "boolean",
				Description: "Perform shallow clone for faster analysis",
			},
		},
		Required: []string{
			"repo_url",
		},
		AdditionalProperties: &[]bool{false}[0],
	}
)
