# Sampling strategies configuration
version: "1.0.0"

# Define available sampling strategies (ordered lists of prompts)
strategies:
  dockerfile:
    - "dockerfile-generation"

  k8s:
    - "k8s-manifest-generation"

  generic:
    - "generic-generation"

# Strategy selection rules based on context
selection_rules:
  dockerfile:
    conditions:
      - key: "language"
        value: "java"
        strategy_index: 0
      - key: "language"
        value: "python"
        strategy_index: 0
      - key: "language"
        value: "nodejs"
        strategy_index: 0
    default_strategy_index: 0

  k8s:
    conditions:
      - key: "type"
        value: "deployment"
        strategy_index: 0
      - key: "type"
        value: "service"
        strategy_index: 0
    default_strategy_index: 0

  generic:
    conditions: []
    default_strategy_index: 0