package errors

// ErrorCode represents an error code
type ErrorCode string

// Build domain error codes
const (
	// Build configuration errors
	BUILD_CONFIG_INVALID     ErrorCode = "BUILD_CONFIG_INVALID"
	BUILD_DOCKERFILE_MISSING ErrorCode = "BUILD_DOCKERFILE_MISSING"
	BUILD_DOCKERFILE_INVALID ErrorCode = "BUILD_DOCKERFILE_INVALID"
	BUILD_CONTEXT_INVALID    ErrorCode = "BUILD_CONTEXT_INVALID"
	BUILD_ARGS_INVALID       ErrorCode = "BUILD_ARGS_INVALID"

	// Build dependency errors
	BUILD_DEPENDENCY_MISSING  ErrorCode = "BUILD_DEPENDENCY_MISSING"
	BUILD_DEPENDENCY_CONFLICT ErrorCode = "BUILD_DEPENDENCY_CONFLICT"
	BUILD_BASE_IMAGE_MISSING  ErrorCode = "BUILD_BASE_IMAGE_MISSING"
	BUILD_BASE_IMAGE_INVALID  ErrorCode = "BUILD_BASE_IMAGE_INVALID"

	// Build execution errors
	BUILD_EXECUTION_FAILED ErrorCode = "BUILD_EXECUTION_FAILED"
	BUILD_COMPILE_FAILED   ErrorCode = "BUILD_COMPILE_FAILED"
	BUILD_LAYER_FAILED     ErrorCode = "BUILD_LAYER_FAILED"
	BUILD_CACHE_FAILED     ErrorCode = "BUILD_CACHE_FAILED"

	// Image operations
	BUILD_IMAGE_TAG_FAILED    ErrorCode = "BUILD_IMAGE_TAG_FAILED"
	BUILD_IMAGE_PUSH_FAILED   ErrorCode = "BUILD_IMAGE_PUSH_FAILED"
	BUILD_IMAGE_PULL_FAILED   ErrorCode = "BUILD_IMAGE_PULL_FAILED"
	BUILD_IMAGE_REMOVE_FAILED ErrorCode = "BUILD_IMAGE_REMOVE_FAILED"

	// Build resources
	BUILD_DISK_SPACE_EXCEEDED ErrorCode = "BUILD_DISK_SPACE_EXCEEDED"
	BUILD_MEMORY_EXCEEDED     ErrorCode = "BUILD_MEMORY_EXCEEDED"
	BUILD_TIMEOUT_EXCEEDED    ErrorCode = "BUILD_TIMEOUT_EXCEEDED"
	BUILD_NETWORK_FAILED      ErrorCode = "BUILD_NETWORK_FAILED"
)
