package errors

// Common error codes used across domains
const (
	// General validation errors
	VALIDATION_FAILED           ErrorCode = "VALIDATION_FAILED"
	VALIDATION_SCHEMA_INVALID   ErrorCode = "VALIDATION_SCHEMA_INVALID"
	VALIDATION_REQUIRED_MISSING ErrorCode = "VALIDATION_REQUIRED_MISSING"
	VALIDATION_FORMAT_INVALID   ErrorCode = "VALIDATION_FORMAT_INVALID"
	VALIDATION_RANGE_INVALID    ErrorCode = "VALIDATION_RANGE_INVALID"

	// Network and connectivity errors
	NETWORK_ERROR                 ErrorCode = "NETWORK_ERROR"
	NETWORK_TIMEOUT               ErrorCode = "NETWORK_TIMEOUT"
	NETWORK_CONNECTION_REFUSED    ErrorCode = "NETWORK_CONNECTION_REFUSED"
	NETWORK_DNS_RESOLUTION_FAILED ErrorCode = "NETWORK_DNS_RESOLUTION_FAILED"
	NETWORK_UNREACHABLE           ErrorCode = "NETWORK_UNREACHABLE"

	// Timeout errors
	TIMEOUT                   ErrorCode = "TIMEOUT"
	TIMEOUT_EXCEEDED          ErrorCode = "TIMEOUT_EXCEEDED"
	TIMEOUT_DEADLINE_EXCEEDED ErrorCode = "TIMEOUT_DEADLINE_EXCEEDED"

	// Resource errors
	RESOURCE_NOT_FOUND      ErrorCode = "RESOURCE_NOT_FOUND"
	RESOURCE_ALREADY_EXISTS ErrorCode = "RESOURCE_ALREADY_EXISTS"
	RESOURCE_EXHAUSTED      ErrorCode = "RESOURCE_EXHAUSTED"
	RESOURCE_LOCKED         ErrorCode = "RESOURCE_LOCKED"
	RESOURCE_UNAVAILABLE    ErrorCode = "RESOURCE_UNAVAILABLE"

	// File system errors
	FILE_NOT_FOUND         ErrorCode = "FILE_NOT_FOUND"
	FILE_PERMISSION_DENIED ErrorCode = "FILE_PERMISSION_DENIED"
	FILE_ALREADY_EXISTS    ErrorCode = "FILE_ALREADY_EXISTS"
	FILE_IO_ERROR          ErrorCode = "FILE_IO_ERROR"
	DIRECTORY_NOT_FOUND    ErrorCode = "DIRECTORY_NOT_FOUND"

	// Configuration errors
	CONFIG_INVALID        ErrorCode = "CONFIG_INVALID"
	CONFIG_MISSING        ErrorCode = "CONFIG_MISSING"
	CONFIG_PARSE_ERROR    ErrorCode = "CONFIG_PARSE_ERROR"
	CONFIG_FORMAT_INVALID ErrorCode = "CONFIG_FORMAT_INVALID"

	// System errors
	SYSTEM_ERROR       ErrorCode = "SYSTEM_ERROR"
	SYSTEM_UNAVAILABLE ErrorCode = "SYSTEM_UNAVAILABLE"
	SYSTEM_OVERLOADED  ErrorCode = "SYSTEM_OVERLOADED"
	SYSTEM_MAINTENANCE ErrorCode = "SYSTEM_MAINTENANCE"
)
