package errors

// Deploy domain error codes
const (
	// Deployment configuration errors
	DEPLOY_CONFIG_INVALID    ErrorCode = "DEPLOY_CONFIG_INVALID"
	DEPLOY_MANIFEST_INVALID  ErrorCode = "DEPLOY_MANIFEST_INVALID"
	DEPLOY_MANIFEST_MISSING  ErrorCode = "DEPLOY_MANIFEST_MISSING"
	DEPLOY_NAMESPACE_INVALID ErrorCode = "DEPLOY_NAMESPACE_INVALID"
	DEPLOY_YAML_SYNTAX_ERROR ErrorCode = "DEPLOY_YAML_SYNTAX_ERROR"

	// Kubernetes cluster errors
	DEPLOY_CLUSTER_UNREACHABLE            ErrorCode = "DEPLOY_CLUSTER_UNREACHABLE"
	DEPLOY_CLUSTER_AUTH_FAILED            ErrorCode = "DEPLOY_CLUSTER_AUTH_FAILED"
	DEPLOY_CLUSTER_VERSION_INCOMPATIBLE   ErrorCode = "DEPLOY_CLUSTER_VERSION_INCOMPATIBLE"
	DEPLOY_CLUSTER_RESOURCES_INSUFFICIENT ErrorCode = "DEPLOY_CLUSTER_RESOURCES_INSUFFICIENT"

	// Deployment execution errors
	DEPLOY_EXECUTION_FAILED ErrorCode = "DEPLOY_EXECUTION_FAILED"
	DEPLOY_ROLLOUT_FAILED   ErrorCode = "DEPLOY_ROLLOUT_FAILED"
	DEPLOY_SERVICE_FAILED   ErrorCode = "DEPLOY_SERVICE_FAILED"
	DEPLOY_INGRESS_FAILED   ErrorCode = "DEPLOY_INGRESS_FAILED"
	DEPLOY_CONFIGMAP_FAILED ErrorCode = "DEPLOY_CONFIGMAP_FAILED"
	DEPLOY_SECRET_FAILED    ErrorCode = "DEPLOY_SECRET_FAILED"

	// Resource errors
	DEPLOY_RESOURCE_EXISTS         ErrorCode = "DEPLOY_RESOURCE_EXISTS"
	DEPLOY_RESOURCE_NOT_FOUND      ErrorCode = "DEPLOY_RESOURCE_NOT_FOUND"
	DEPLOY_RESOURCE_CONFLICT       ErrorCode = "DEPLOY_RESOURCE_CONFLICT"
	DEPLOY_RESOURCE_QUOTA_EXCEEDED ErrorCode = "DEPLOY_RESOURCE_QUOTA_EXCEEDED"

	// Validation errors
	DEPLOY_VALIDATION_FAILED          ErrorCode = "DEPLOY_VALIDATION_FAILED"
	DEPLOY_SCHEMA_VALIDATION_FAILED   ErrorCode = "DEPLOY_SCHEMA_VALIDATION_FAILED"
	DEPLOY_SECURITY_VALIDATION_FAILED ErrorCode = "DEPLOY_SECURITY_VALIDATION_FAILED"

	// Monitoring and health checks
	DEPLOY_HEALTH_CHECK_FAILED    ErrorCode = "DEPLOY_HEALTH_CHECK_FAILED"
	DEPLOY_READINESS_PROBE_FAILED ErrorCode = "DEPLOY_READINESS_PROBE_FAILED"
	DEPLOY_LIVENESS_PROBE_FAILED  ErrorCode = "DEPLOY_LIVENESS_PROBE_FAILED"
)
