package errors

// Security domain error codes
const (
	// Vulnerability scanning errors
	SECURITY_VULNERABILITY_CRITICAL ErrorCode = "SECURITY_VULNERABILITY_CRITICAL"
	SECURITY_VULNERABILITY_HIGH     ErrorCode = "SECURITY_VULNERABILITY_HIGH"
	SECURITY_VULNERABILITY_MEDIUM   ErrorCode = "SECURITY_VULNERABILITY_MEDIUM"
	SECURITY_VULNERABILITY_LOW      ErrorCode = "SECURITY_VULNERABILITY_LOW"
	SECURITY_SCAN_FAILED            ErrorCode = "SECURITY_SCAN_FAILED"
	SECURITY_SCAN_TIMEOUT           ErrorCode = "SECURITY_SCAN_TIMEOUT"

	// Security configuration errors
	SECURITY_CONFIG_INVALID      ErrorCode = "SECURITY_CONFIG_INVALID"
	SECURITY_POLICY_VIOLATION    ErrorCode = "SECURITY_POLICY_VIOLATION"
	SECURITY_POLICY_NOT_FOUND    ErrorCode = "SECURITY_POLICY_NOT_FOUND"
	SECURITY_SCANNER_UNAVAILABLE ErrorCode = "SECURITY_SCANNER_UNAVAILABLE"
	SECURITY_DATABASE_OUTDATED   ErrorCode = "SECURITY_DATABASE_OUTDATED"

	// Access and authentication errors
	SECURITY_ACCESS_DENIED         ErrorCode = "SECURITY_ACCESS_DENIED"
	SECURITY_AUTHENTICATION_FAILED ErrorCode = "SECURITY_AUTHENTICATION_FAILED"
	SECURITY_AUTHORIZATION_FAILED  ErrorCode = "SECURITY_AUTHORIZATION_FAILED"
	SECURITY_TOKEN_EXPIRED         ErrorCode = "SECURITY_TOKEN_EXPIRED"
	SECURITY_TOKEN_INVALID         ErrorCode = "SECURITY_TOKEN_INVALID"

	// Secrets and credentials errors
	SECURITY_SECRET_NOT_FOUND    ErrorCode = "SECURITY_SECRET_NOT_FOUND"
	SECURITY_SECRET_INVALID      ErrorCode = "SECURITY_SECRET_INVALID"
	SECURITY_CREDENTIAL_LEAKED   ErrorCode = "SECURITY_CREDENTIAL_LEAKED"
	SECURITY_CERTIFICATE_INVALID ErrorCode = "SECURITY_CERTIFICATE_INVALID"
	SECURITY_CERTIFICATE_EXPIRED ErrorCode = "SECURITY_CERTIFICATE_EXPIRED"

	// Compliance errors
	SECURITY_COMPLIANCE_VIOLATION ErrorCode = "SECURITY_COMPLIANCE_VIOLATION"
	SECURITY_AUDIT_FAILED         ErrorCode = "SECURITY_AUDIT_FAILED"
	SECURITY_BASELINE_VIOLATION   ErrorCode = "SECURITY_BASELINE_VIOLATION"
)
