package codes

import "github.com/Azure/container-kit/pkg/mcp/domain/errors"

// Build domain error codes
const (
	// Build configuration errors
	BUILD_CONFIG_INVALID     errors.ErrorCode = "BUILD_CONFIG_INVALID"
	BUILD_DOCKERFILE_MISSING errors.ErrorCode = "BUILD_DOCKERFILE_MISSING"
	BUILD_DOCKERFILE_INVALID errors.ErrorCode = "BUILD_DOCKERFILE_INVALID"
	BUILD_CONTEXT_INVALID    errors.ErrorCode = "BUILD_CONTEXT_INVALID"
	BUILD_ARGS_INVALID       errors.ErrorCode = "BUILD_ARGS_INVALID"

	// Build dependency errors
	BUILD_DEPENDENCY_MISSING  errors.ErrorCode = "BUILD_DEPENDENCY_MISSING"
	BUILD_DEPENDENCY_CONFLICT errors.ErrorCode = "BUILD_DEPENDENCY_CONFLICT"
	BUILD_BASE_IMAGE_MISSING  errors.ErrorCode = "BUILD_BASE_IMAGE_MISSING"
	BUILD_BASE_IMAGE_INVALID  errors.ErrorCode = "BUILD_BASE_IMAGE_INVALID"

	// Build execution errors
	BUILD_EXECUTION_FAILED errors.ErrorCode = "BUILD_EXECUTION_FAILED"
	BUILD_COMPILE_FAILED   errors.ErrorCode = "BUILD_COMPILE_FAILED"
	BUILD_LAYER_FAILED     errors.ErrorCode = "BUILD_LAYER_FAILED"
	BUILD_CACHE_FAILED     errors.ErrorCode = "BUILD_CACHE_FAILED"

	// Image operations
	BUILD_IMAGE_TAG_FAILED    errors.ErrorCode = "BUILD_IMAGE_TAG_FAILED"
	BUILD_IMAGE_PUSH_FAILED   errors.ErrorCode = "BUILD_IMAGE_PUSH_FAILED"
	BUILD_IMAGE_PULL_FAILED   errors.ErrorCode = "BUILD_IMAGE_PULL_FAILED"
	BUILD_IMAGE_REMOVE_FAILED errors.ErrorCode = "BUILD_IMAGE_REMOVE_FAILED"

	// Build resources
	BUILD_DISK_SPACE_EXCEEDED errors.ErrorCode = "BUILD_DISK_SPACE_EXCEEDED"
	BUILD_MEMORY_EXCEEDED     errors.ErrorCode = "BUILD_MEMORY_EXCEEDED"
	BUILD_TIMEOUT_EXCEEDED    errors.ErrorCode = "BUILD_TIMEOUT_EXCEEDED"
	BUILD_NETWORK_FAILED      errors.ErrorCode = "BUILD_NETWORK_FAILED"
)
