package codes

import "github.com/Azure/container-kit/pkg/mcp/domain/errors"

// Deploy domain error codes
const (
	// Deployment configuration errors
	DEPLOY_CONFIG_INVALID    errors.ErrorCode = "DEPLOY_CONFIG_INVALID"
	DEPLOY_MANIFEST_INVALID  errors.ErrorCode = "DEPLOY_MANIFEST_INVALID"
	DEPLOY_MANIFEST_MISSING  errors.ErrorCode = "DEPLOY_MANIFEST_MISSING"
	DEPLOY_NAMESPACE_INVALID errors.ErrorCode = "DEPLOY_NAMESPACE_INVALID"
	DEPLOY_YAML_SYNTAX_ERROR errors.ErrorCode = "DEPLOY_YAML_SYNTAX_ERROR"

	// Kubernetes cluster errors
	DEPLOY_CLUSTER_UNREACHABLE            errors.ErrorCode = "DEPLOY_CLUSTER_UNREACHABLE"
	DEPLOY_CLUSTER_AUTH_FAILED            errors.ErrorCode = "DEPLOY_CLUSTER_AUTH_FAILED"
	DEPLOY_CLUSTER_VERSION_INCOMPATIBLE   errors.ErrorCode = "DEPLOY_CLUSTER_VERSION_INCOMPATIBLE"
	DEPLOY_CLUSTER_RESOURCES_INSUFFICIENT errors.ErrorCode = "DEPLOY_CLUSTER_RESOURCES_INSUFFICIENT"

	// Deployment execution errors
	DEPLOY_EXECUTION_FAILED errors.ErrorCode = "DEPLOY_EXECUTION_FAILED"
	DEPLOY_ROLLOUT_FAILED   errors.ErrorCode = "DEPLOY_ROLLOUT_FAILED"
	DEPLOY_SERVICE_FAILED   errors.ErrorCode = "DEPLOY_SERVICE_FAILED"
	DEPLOY_INGRESS_FAILED   errors.ErrorCode = "DEPLOY_INGRESS_FAILED"
	DEPLOY_CONFIGMAP_FAILED errors.ErrorCode = "DEPLOY_CONFIGMAP_FAILED"
	DEPLOY_SECRET_FAILED    errors.ErrorCode = "DEPLOY_SECRET_FAILED"

	// Resource errors
	DEPLOY_RESOURCE_EXISTS         errors.ErrorCode = "DEPLOY_RESOURCE_EXISTS"
	DEPLOY_RESOURCE_NOT_FOUND      errors.ErrorCode = "DEPLOY_RESOURCE_NOT_FOUND"
	DEPLOY_RESOURCE_CONFLICT       errors.ErrorCode = "DEPLOY_RESOURCE_CONFLICT"
	DEPLOY_RESOURCE_QUOTA_EXCEEDED errors.ErrorCode = "DEPLOY_RESOURCE_QUOTA_EXCEEDED"

	// Validation errors
	DEPLOY_VALIDATION_FAILED          errors.ErrorCode = "DEPLOY_VALIDATION_FAILED"
	DEPLOY_SCHEMA_VALIDATION_FAILED   errors.ErrorCode = "DEPLOY_SCHEMA_VALIDATION_FAILED"
	DEPLOY_SECURITY_VALIDATION_FAILED errors.ErrorCode = "DEPLOY_SECURITY_VALIDATION_FAILED"

	// Monitoring and health checks
	DEPLOY_HEALTH_CHECK_FAILED    errors.ErrorCode = "DEPLOY_HEALTH_CHECK_FAILED"
	DEPLOY_READINESS_PROBE_FAILED errors.ErrorCode = "DEPLOY_READINESS_PROBE_FAILED"
	DEPLOY_LIVENESS_PROBE_FAILED  errors.ErrorCode = "DEPLOY_LIVENESS_PROBE_FAILED"
)
