package codes

import "github.com/Azure/container-kit/pkg/mcp/domain/errors"

// Security domain error codes
const (
	// Vulnerability scanning errors
	SECURITY_VULNERABILITY_CRITICAL errors.ErrorCode = "SECURITY_VULNERABILITY_CRITICAL"
	SECURITY_VULNERABILITY_HIGH     errors.ErrorCode = "SECURITY_VULNERABILITY_HIGH"
	SECURITY_VULNERABILITY_MEDIUM   errors.ErrorCode = "SECURITY_VULNERABILITY_MEDIUM"
	SECURITY_VULNERABILITY_LOW      errors.ErrorCode = "SECURITY_VULNERABILITY_LOW"
	SECURITY_SCAN_FAILED            errors.ErrorCode = "SECURITY_SCAN_FAILED"
	SECURITY_SCAN_TIMEOUT           errors.ErrorCode = "SECURITY_SCAN_TIMEOUT"

	// Security configuration errors
	SECURITY_CONFIG_INVALID      errors.ErrorCode = "SECURITY_CONFIG_INVALID"
	SECURITY_POLICY_VIOLATION    errors.ErrorCode = "SECURITY_POLICY_VIOLATION"
	SECURITY_POLICY_NOT_FOUND    errors.ErrorCode = "SECURITY_POLICY_NOT_FOUND"
	SECURITY_SCANNER_UNAVAILABLE errors.ErrorCode = "SECURITY_SCANNER_UNAVAILABLE"
	SECURITY_DATABASE_OUTDATED   errors.ErrorCode = "SECURITY_DATABASE_OUTDATED"

	// Access and authentication errors
	SECURITY_ACCESS_DENIED         errors.ErrorCode = "SECURITY_ACCESS_DENIED"
	SECURITY_AUTHENTICATION_FAILED errors.ErrorCode = "SECURITY_AUTHENTICATION_FAILED"
	SECURITY_AUTHORIZATION_FAILED  errors.ErrorCode = "SECURITY_AUTHORIZATION_FAILED"
	SECURITY_TOKEN_EXPIRED         errors.ErrorCode = "SECURITY_TOKEN_EXPIRED"
	SECURITY_TOKEN_INVALID         errors.ErrorCode = "SECURITY_TOKEN_INVALID"

	// Secrets and credentials errors
	SECURITY_SECRET_NOT_FOUND    errors.ErrorCode = "SECURITY_SECRET_NOT_FOUND"
	SECURITY_SECRET_INVALID      errors.ErrorCode = "SECURITY_SECRET_INVALID"
	SECURITY_CREDENTIAL_LEAKED   errors.ErrorCode = "SECURITY_CREDENTIAL_LEAKED"
	SECURITY_CERTIFICATE_INVALID errors.ErrorCode = "SECURITY_CERTIFICATE_INVALID"
	SECURITY_CERTIFICATE_EXPIRED errors.ErrorCode = "SECURITY_CERTIFICATE_EXPIRED"

	// Compliance errors
	SECURITY_COMPLIANCE_VIOLATION errors.ErrorCode = "SECURITY_COMPLIANCE_VIOLATION"
	SECURITY_AUDIT_FAILED         errors.ErrorCode = "SECURITY_AUDIT_FAILED"
	SECURITY_BASELINE_VIOLATION   errors.ErrorCode = "SECURITY_BASELINE_VIOLATION"
)
