mcpServers:
  filesystem:
    type: "builtin"
    name: "fs"
  
  bash:
    type: "builtin"
    name: "bash"

  containerization-assist:
    type: "stdio"
    command: "/Users/reiniercc/Documents/repos/container-copilot/containerization-assist-mcp"
    args: []

model: "azure:${env://AZURE_OPENAI_DEPLOYMENT_ID}"
provider-api-key: "${env://AZURE_OPENAI_KEY}"
provider-url: "${env://AZURE_OPENAI_ENDPOINT}"
