# MCP Configuration File
# This file contains example configuration for the MCP server
# Copy this to mcp.yaml and modify as needed

# Server configuration
server:
  host: "localhost"
  port: 8080
  read_timeout: "30s"
  write_timeout: "30s"
  max_request_size: 10485760  # 10MB in bytes
  enable_profiling: false
  profiling_port: 6060
  log_level: "info"  # debug, info, warn, error
  enable_metrics: true
  metrics_port: 9090
  workspace_base: "/tmp/mcp-workspaces"
  max_concurrent_sessions: 10

# AI Analyzer configuration
analyzer:
  enable_ai: false
  ai_log_level: "info"
  max_analysis_time: "5m"
  enable_file_detection: true
  enable_language_detection: true
  enable_dependency_scanning: true
  cache_results: true
  cache_ttl: "1h"

# Transport configuration
transport:
  type: "stdio"  # stdio, http, grpc
  buffer_size: 8192
  read_timeout: "30s"
  write_timeout: "30s"
  enable_compression: false
  log_level: "info"

# Observability configuration
observability:
  enable_tracing: true
  enable_metrics: true
  enable_logging: true
  otel_endpoint: ""  # OpenTelemetry endpoint
  service_name: "mcp-server"
  service_version: "1.0.0"
  metrics_interval: "30s"
  sampling_rate: "0.1"

# Docker configuration
docker:
  username: ""  # Docker registry username
  password: ""  # Docker registry password
  registry: "docker.io"
  timeout: "60s"
  enable_cache: true
  build_timeout: "10m"
  push_timeout: "5m"
  pull_timeout: "5m"
  max_concurrent: 3

# Environment variables can also be used to override any configuration value
# Format: MCP_<SECTION>_<FIELD_NAME>
# Example:
#   MCP_SERVER_PORT=8080
#   MCP_ANALYZER_ENABLE_AI=true
#   MCP_DOCKER_USERNAME=myuser
#   MCP_DOCKER_PASSWORD=mypassword
