// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package composition

import (
	"github.com/Azure/container-kit/pkg/mcp/api"
	"github.com/Azure/container-kit/pkg/mcp/application"
	"github.com/Azure/container-kit/pkg/mcp/domain/workflow"
	"github.com/Azure/container-kit/pkg/mcp/infrastructure/ai_ml/ml"
	"github.com/Azure/container-kit/pkg/mcp/infrastructure/ai_ml/sampling"
	"github.com/Azure/container-kit/pkg/mcp/infrastructure/messaging/events"
	"github.com/Azure/container-kit/pkg/mcp/infrastructure/messaging/progress"
	"github.com/Azure/container-kit/pkg/mcp/infrastructure/orchestration/steps"
	"log/slog"
)

// Injectors from server.go:

// InitializeServer is the single entry point used by main().
func InitializeServer(logger *slog.Logger, config workflow.ServerConfig) (api.MCPServer, error) {
	optimizedSessionManager, err := provideSessionManager(config, logger)
	if err != nil {
		return nil, err
	}
	store := provideResourceStore(logger)
	directProgressFactory := progress.NewDirectProgressFactory(logger)
	publisher := events.NewPublisher(logger)
	stepProvider := steps.NewRegistryStepProvider()
	dagOrchestrator, err := provideDAGOrchestrator(stepProvider, directProgressFactory, logger)
	if err != nil {
		return nil, err
	}
	client, err := provideSamplingClient(logger)
	if err != nil {
		return nil, err
	}
	domainAdapter := sampling.NewDomainAdapter(client)
	advancedPatternRecognizer := ml.NewAdvancedPatternRecognizer(domainAdapter, logger)
	enhancedErrorHandler := ml.NewEnhancedErrorHandler(domainAdapter, publisher, logger)
	stepEnhancer := ml.NewStepEnhancer(enhancedErrorHandler, logger)
	manager, err := providePromptManager(logger)
	if err != nil {
		return nil, err
	}
	dependencies := provideDependencies(logger, config, optimizedSessionManager, store, directProgressFactory, publisher, dagOrchestrator, advancedPatternRecognizer, enhancedErrorHandler, stepEnhancer, domainAdapter, manager)
	mcpServer, err := application.ProvideServer(dependencies)
	if err != nil {
		return nil, err
	}
	return mcpServer, nil
}
