# Container Kit MCP Server Configuration
# This file shows all available configuration options

# Server settings
workspace_dir: /tmp/mcp-workspace
store_path: /tmp/mcp-store/sessions.db
session_ttl: 24h
max_sessions: 100
max_disk_per_session: 104857600  # 100MB in bytes
total_disk_limit: 1073741824      # 1GB in bytes

# Transport settings
transport_type: stdio  # Options: stdio, http
http_addr: 0.0.0.0
http_port: 8080
cors_origins:
  - "*"

# Logging settings
log_level: info  # Options: debug, info, warn, error

# Prompt template settings
prompt_template_dir: ""  # Leave empty to use embedded templates
prompt_hot_reload: false
prompt_allow_override: false

# AI sampling settings
sampling_endpoint: ""  # Azure OpenAI endpoint
sampling_api_key: ""   # Azure OpenAI API key
sampling_max_tokens: 4096
sampling_temperature: 0.7