id: "repository-analysis"
name: "Repository Analysis Enhancement"
description: "Improves repository analysis with AI insights"
version: "1.0.0"
category: "analysis"
template: |
  Improve this repository analysis by identifying additional details:

  Initial Analysis:
  {{.InitialAnalysis}}

  Repository Structure:
  {{.FileTree}}

  README Content:
  {{.ReadmeContent}}

  Please enhance the analysis with:
  1. More accurate language/framework detection
  2. Identification of build tools and package managers
  3. Detection of required services (databases, caches, message queues)
  4. Application entry points and main executable
  5. Environment variables and configuration requirements
  6. Suggested port numbers based on framework conventions
  7. Special build requirements or dependencies

  Return an enhanced analysis that will help with containerization.

system_prompt: "You are a software architecture expert. Analyze repositories to understand their structure and requirements."
parameters:
  - name: "InitialAnalysis"
    type: "string"
    description: "Initial automated analysis results"
    required: true
  - name: "FileTree"
    type: "string"
    description: "Repository file structure"
    required: true
  - name: "ReadmeContent"
    type: "string"
    description: "README file content"
    required: false
    default: ""
defaults:
  ReadmeContent: "No README available"
max_tokens: 1500
temperature: 0.3
tags: ["analysis", "repository", "architecture", "detection"]
created_at: 2025-01-12T00:00:00Z
updated_at: 2025-01-12T00:00:00Z