trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

steps:
  - checkout: self

  - task: ComponentGovernanceComponentDetection@0
    displayName: Component Detection

  - task: notice@0
    displayName: Generate NOTICE file
    inputs:
      outputfile: $(System.DefaultWorkingDirectory)/obj/NOTICE
      outputformat: text