name: Build & Publish
on: [workflow_dispatch]

permissions:
  contents: read

jobs:
  Build:
      name: release
      runs-on: ubuntu-latest
      permissions: 
        actions: read
        contents: read
        deployments: read
        packages: none
      steps:
        
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Use Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: 20

      # Run install dependencies
      - name: Install dependencies
        run: npm ci

      # Ensure project builds successfully before creating release
      - name: Build 
        run: npm run build

      - name: Get current version from package.json
        id: package_version
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "Version=$VERSION"
          echo "current-version=$VERSION" >> $GITHUB_OUTPUT

      outputs:
        current-version: ${{ steps.package_version.outputs.current-version }}

  Publish:
    name: publish
    runs-on: ubuntu-latest
    needs: Build
    permissions: 
        actions: read
        contents: write
        deployments: read
        packages: none
        id-token: write
    env: 
      current-version: ${{ needs.Build.outputs.current-version }}
    steps:

      # Checkout the code again for release
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Use Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: 20

      # Run install dependencies
      - name: Install dependencies
        run: npm ci

      - name: Build 
        run: npm run build

      - name: Create target package
        run: npm pack

      - name: federated login
        uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2.3.0
        with:
          client-id: ${{ secrets.AZURE_PARTNER_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_PARTNER_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_PARTNER_SUBSCRIPTION_ID }}

      # az storage blob upload -f ${Folder to Copy} -c ${drops/<BlobPath>} --account-name azuresdkpartnerdrops --auth-mode login
      - name: Upload files to partner drop folder
        run: |
            az account show
            VERSION=${{ env.current-version }}
            BLOBPATH="drops/containerization-assist/js/$VERSION"
            echo "Uploading package version $VERSION to blob path $BLOBPATH"
            az storage blob upload -f "./azure-containerization-assist-mcp-$VERSION.tgz" -c "$BLOBPATH" --account-name azuresdkpartnerdrops --auth-mode login
