name: Unit Tests

on:
  pull_request:
    branches:
      - main

jobs:
  # Core packages (no build tags)
  core-test:
    name: Core Packages
    uses: ./.github/workflows/reusable-go-build.yml
    with:
      go-version: '1.24'
      packages: './pkg/core/... ./pkg/pipeline/... ./pkg/utils/... ./pkg/docker/... ./pkg/k8s/... ./pkg/kind/...'
      run-tests: true
      run-race-tests: true
      run-lint: true
      lint-args: '--timeout=5m --config=.golangci.yml'
      lint-error-threshold: 50
      lint-warn-threshold: 30
      coverage: true

  # MCP packages
  mcp-test:
    name: MCP Packages
    uses: ./.github/workflows/reusable-go-build.yml
    with:
      go-version: '1.24'
      packages: './pkg/mcp/...'
      run-tests: true
      run-race-tests: true
      run-lint: true
      lint-args: '--timeout=5m --config=.golangci.yml'
      lint-error-threshold: 100  # Higher threshold for MCP as it has more issues currently
      lint-warn-threshold: 50
      coverage: true

  # CLI packages
  cli-test:
    name: CLI Packages
    uses: ./.github/workflows/reusable-go-build.yml
    with:
      go-version: '1.24'
      packages: './pkg/ai/...'
      run-tests: true
      run-race-tests: true
      run-lint: true
      lint-args: '--timeout=5m --config=.golangci.yml'
      lint-error-threshold: 50
      lint-warn-threshold: 30
      coverage: true

  # Build CLI binary
  build-cli:
    name: Build CLI Binary
    uses: ./.github/workflows/reusable-go-build.yml
    with:
      go-version: '1.24'
      packages: './cmd/...'
      run-tests: false
      build-binary: true
      binary-output: 'container-kit'
      binary-main: './main.go'

  # Build MCP server (no tags needed)
  build-mcp:
    name: Build MCP Server
    uses: ./.github/workflows/reusable-go-build.yml
    with:
      go-version: '1.24'
      packages: './cmd/mcp-server/...'
      run-tests: false
      build-binary: true
      binary-output: 'container-kit-mcp'
      binary-main: './cmd/mcp-server'
